#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 002: Verbum Implementation

set -e

echo "========================================"
echo "Starting Verbum Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Python 3.11+
PYTHON_VERSION=$(python3 --version 2>/dev/null | grep -oP '\d+\.\d+' | head -1)
if [ -z "$PYTHON_VERSION" ]; then
    echo -e "${RED}Python 3.11+ is required but not found${NC}"
    exit 1
fi
echo -e "${GREEN}Python $PYTHON_VERSION found${NC}"

# Node.js
if command -v node &>/dev/null; then
    NODE_VERSION=$(node --version 2>/dev/null)
    echo -e "${GREEN}Node.js $NODE_VERSION found${NC}"
else
    echo -e "${YELLOW}Node.js not found in PATH. Attempting nvm...${NC}"
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
    if command -v node &>/dev/null; then
        NODE_VERSION=$(node --version)
        echo -e "${GREEN}Node.js $NODE_VERSION found (via nvm)${NC}"
    else
        echo -e "${RED}Node.js is required but not found${NC}"
        exit 1
    fi
fi

# ============================================
# BACKEND SETUP
# ============================================

echo ""
echo "Setting up Backend..."

BACKEND_DIR="$PROJECT_ROOT/backend"

if [ ! -d "$BACKEND_DIR" ]; then
    echo -e "${RED}Backend directory not found at $BACKEND_DIR${NC}"
    echo "Run the implementation first to create the backend project structure."
    exit 1
fi

cd "$BACKEND_DIR"

# Create venv if not exists
if [ ! -d "venv" ]; then
    echo "Creating Python virtual environment..."
    python3 -m venv venv
fi

source venv/bin/activate

# Install dependencies
if [ -f "requirements.txt" ]; then
    echo "Installing Python dependencies..."
    pip install -r requirements.txt -q
fi

# Check .env
if [ ! -f ".env" ] && [ -f ".env.example" ]; then
    echo -e "${YELLOW}No .env found. Copying .env.example...${NC}"
    cp .env.example .env
    echo -e "${YELLOW}Please configure API keys in backend/.env${NC}"
fi

# Start backend
echo "Starting FastAPI backend on port 8000..."
uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!

cd "$PROJECT_ROOT"

# ============================================
# FRONTEND SETUP
# ============================================

echo ""
echo "Setting up Frontend..."

FRONTEND_DIR="$PROJECT_ROOT/frontend"

if [ ! -d "$FRONTEND_DIR" ]; then
    echo -e "${RED}Frontend directory not found at $FRONTEND_DIR${NC}"
    echo "Run the implementation first to create the frontend project structure."
    exit 1
fi

cd "$FRONTEND_DIR"

# Install dependencies
if [ -d "node_modules" ]; then
    echo "Node modules already installed."
else
    echo "Installing Node.js dependencies..."
    npm install
fi

# Start frontend
echo "Starting Vite dev server on port 5173..."
npm run dev &
FRONTEND_PID=$!

cd "$PROJECT_ROOT"

# ============================================
# WAIT FOR SERVICES
# ============================================

echo ""
wait_for_service 8000 "Backend (FastAPI)"
wait_for_service 5173 "Frontend (Vite)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Verbum Development Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:    http://localhost:8000"
echo "  API Docs:       http://localhost:8000/docs"
echo "  Frontend:       http://localhost:5173"
echo ""
echo "Process IDs:"
echo "  Backend PID:    $BACKEND_PID"
echo "  Frontend PID:   $FRONTEND_PID"
echo ""
echo "To stop all services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""

# Keep script running to maintain child processes
wait
