#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Project: Musicalizer — AI Music Generation, Evaluation & Auto-Improvement Pipeline

set -e

echo "========================================"
echo "Musicalizer — Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

PROJECT_DIR="/home/rlmit/workspace/musicalizer"

# ============================================
# PREREQUISITES CHECK
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Python version
PYTHON_VERSION=$(python3 --version 2>/dev/null | cut -d' ' -f2 | cut -d'.' -f1,2)
if [ -z "$PYTHON_VERSION" ]; then
    echo -e "${RED}Python 3 not found. Please install Python 3.11+${NC}"
    exit 1
fi

PYTHON_MAJOR=$(echo $PYTHON_VERSION | cut -d'.' -f1)
PYTHON_MINOR=$(echo $PYTHON_VERSION | cut -d'.' -f2)

if [ "$PYTHON_MAJOR" -lt 3 ] || ([ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 11 ]); then
    echo -e "${YELLOW}Warning: Python $PYTHON_VERSION detected. Python 3.11+ recommended.${NC}"
else
    echo -e "${GREEN}Python $PYTHON_VERSION OK${NC}"
fi

# ============================================
# VIRTUAL ENVIRONMENT
# ============================================

echo ""
echo "Setting up virtual environment..."

cd "$PROJECT_DIR"

if [ ! -d ".venv" ]; then
    python3 -m venv .venv
    echo -e "${GREEN}Virtual environment created${NC}"
else
    echo -e "${GREEN}Virtual environment already exists${NC}"
fi

source .venv/bin/activate

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

if [ -f "pyproject.toml" ]; then
    pip install -e ".[dev]" --quiet
    echo -e "${GREEN}Dependencies installed${NC}"
else
    echo -e "${YELLOW}pyproject.toml not found — skipping install (will be created in Phase 1)${NC}"
fi

# ============================================
# ENVIRONMENT VARIABLES CHECK
# ============================================

echo ""
echo "Checking environment variables..."

if [ -f ".env" ]; then
    echo -e "${GREEN}.env file found${NC}"
else
    if [ -f ".env.example" ]; then
        echo -e "${YELLOW}.env file not found. Copying from .env.example...${NC}"
        cp .env.example .env
        echo -e "${YELLOW}Please edit .env with your API keys${NC}"
    else
        echo -e "${YELLOW}.env.example not found — will be created in Phase 1${NC}"
    fi
fi

# Check API keys (non-blocking — they're only needed for live tests)
if [ -z "$GEMINI_API_KEY" ]; then
    echo -e "${YELLOW}GEMINI_API_KEY not set (needed for Gemini provider)${NC}"
else
    echo -e "${GREEN}GEMINI_API_KEY is set${NC}"
fi

if [ -z "$CHUTES_API_KEY" ]; then
    echo -e "${YELLOW}CHUTES_API_KEY not set (needed for Chutes provider)${NC}"
else
    echo -e "${GREEN}CHUTES_API_KEY is set${NC}"
fi

# ============================================
# VERIFY SETUP
# ============================================

echo ""
echo "Verifying setup..."

if [ -f "pyproject.toml" ]; then
    python -c "import musicalizer; print(f'musicalizer v{musicalizer.__version__}')" 2>/dev/null && \
        echo -e "${GREEN}Package import OK${NC}" || \
        echo -e "${YELLOW}Package not yet importable (will be ready after Phase 1)${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project Type: Python CLI Application (single service)"
echo "Package:      src/musicalizer/"
echo "Tests:        tests/"
echo "Presets:      presets/"
echo "Output:       output/"
echo ""
echo "Commands (after implementation):"
echo "  python -m musicalizer generate --preset brazilian-catholic --provider gemini"
echo "  python -m musicalizer evaluate --input output/generation.json"
echo "  python -m musicalizer auto-improve --preset brazilian-catholic --iterations 5"
echo "  python -m musicalizer presets list"
echo ""
echo "Testing:"
echo "  pytest tests/ -v"
echo ""
